spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  application:
    name: microservice-config-wancient-dev

---
spring:
  profiles: test
  application:
    name: microservice-config-wancient-test
